/* Generated by reswrap version 4.0.0 */

namespace resources {

/* created by reswrap from file images/zoom_in.gif */
extern const unsigned char zoom_in[4940];

/* created by reswrap from file images/zoom_out.gif */
extern const unsigned char zoom_out[5010];

}
