<?php
// Database information
$host = 'localhost';
$user = 'dignet';
$pass = 'peeterkalleandrei';
$dbname = 'DigNet';

$conn = mysql_connect($host, $user, $pass) or die ('Error opening DB connection');
mysql_select_db($dbname);

// Parameters from user
$projectName = mysql_real_escape_string($_GET['name']);
$headVersion = intval(mysql_real_escape_string($_GET['headVersion']));
$baseVersion = intval(mysql_real_escape_string($_GET['baseVersion']));

if (strcmp($headVersion, $_GET['headVersion'])!=0){
	echo '#warning wrong head version'.$_GET['headVersion']."\n";
	unset($headVersion);
}
if (strcmp($baseVersion, $_GET['baseVersion'])!=0){
	echo '#warning wrong base version'.$_GET['baseVersion']."\n";
	unset($baseVersion);
}
// Variable definitions
$buildNumber;
$buildDate;
$buildProjectId;


// File header
echo "/***********************************************\n";
echo " * File Automatically generated by BuildNumber *\n";
echo " ***********************************************/\n";
echo "\n\n";
echo "/***************\n";
echo " * Parameters: *\n";
print_r($_GET);
echo " ***************/\n\n\n";


// Get information about project
if (isset($projectName)){
	// Find project ID
	$projectsQuery = "select Name, id from ProjectName group by Name";
	$result = mysql_query($projectsQuery);
	$projectId;
	while ($name = mysql_fetch_array($result, MYSQL_ASSOC)){
		if (strcmp($name['Name'], $projectName) == 0){
			$projectId = $name['id'];
		}
	}
	if (!isset($projectId)){
		die("#error no such project: ".$projectName."\n");
	}

	$maxBuildQuery = "SELECT MAX(ProjectBuild.Build_Number) as Build_Number FROM ProjectBuild where ProjectBuild.Project_ID = '".$projectId."'";
	$result = mysql_query($maxBuildQuery);
	$maxBuildNumberResult = mysql_fetch_array($result, MYSQL_ASSOC);
	$maxBuildNumber = $maxBuildNumberResult['Build_Number'];
	// Use the found project ID to get the last build number
	$query = "
		SELECT 
			ProjectBuild.Project_Id, 
			ProjectBuild.Build_Number, 
			ProjectBuild.Build_Version,
			ProjectBuild.Build_Base_Version,
			now() as time 
		FROM 
			ProjectBuild
		WHERE 
			ProjectBuild.Project_ID = ".$projectId."
			AND ProjectBuild.Build_Number = ".$maxBuildNumber."
		GROUP BY 
			ProjectBuild.Project_Id";
	$result = mysql_query($query) or die('#error can\'t find builds for project: '.$projectName."\n");
	$row = mysql_fetch_array($result, MYSQL_ASSOC);

	$lastBuildVersion = $row['Build_Version'];
	$lastBaseBuildVersion = $row['Build_Base_Version'];
	$buildNumber	= $row['Build_Number'];
	// Only increase build number if revision number of base or DigNet has changed
	if (strcmp($lastBuildVersion, $headVersion)!=0 || strcmp($lastBaseBuildVersion, $baseVersion) != 0) {
		$buildNumber	= $buildNumber +1;
	}
	$buildDate	= $row['time'];
	$buildProjectId	= $row['Project_Id'];
	
	if (!isset($buildProjectId)){
		echo "#error can't find project build from DB\n";
	} else {
		if (isset($headVersion)){
			// If head version is not set then do not update database information
			$insert = '
				INSERT INTO ProjectBuild set 
					Project_Id = \''.$buildProjectId.'\', 
					Build_Date = \''.$buildDate.'\', 
					Build_Number = \''.$buildNumber.'\', 
					Build_Version = \''.$headVersion.'\', 
					Build_Base_Version = \''.$baseVersion.'\'';
			mysql_query($insert) or die('#error can\'t update project information: '.$insert);
		} else {
			echo "#warning no revision head version, not updating build number\n\n\n";
		}
	}
	mysql_close($conn);
}

// Print out information

if (isset($buildNumber)){
	echo '#define BUILD_NUMBER '.$buildNumber."\n";
}

if (isset($projectName)){
	echo '#define BUILD_NAME "'.$projectName."\"\n";
}

if (isset($headVersion) && isset($baseVersion)){
	echo '#define BUILD_VERSION "'.$headVersion.".".$baseVersion."\"\n";
}

if (isset($buildDate)){
	echo '#define BUILD_DATE "'.$buildDate."\"\n";
}

?>
