/* Generated by reswrap version 4.0.0 */

namespace resources {

/* created by reswrap from file images/workmark_dredged.bmp */
extern const unsigned char workmark_dredged[2166];

/* created by reswrap from file images/workmark_ok.bmp */
extern const unsigned char workmark_ok[12342];

/* created by reswrap from file images/workmark_problem.bmp */
extern const unsigned char workmark_problem[12342];

/* created by reswrap from file images/zoom_in.gif */
extern const unsigned char zoom_in[4940];

/* created by reswrap from file images/zoom_out.gif */
extern const unsigned char zoom_out[5010];

/* created by reswrap from file images/workmark_icon_dredged.gif */
extern const unsigned char workmark_icon_dredged[423];

/* created by reswrap from file images/workmark_icon_none.gif */
extern const unsigned char workmark_icon_none[423];

/* created by reswrap from file images/workmark_icon_ok.gif */
extern const unsigned char workmark_icon_ok[423];

/* created by reswrap from file images/workmark_icon_problem.gif */
extern const unsigned char workmark_icon_problem[423];

/* created by reswrap from file images/icon_Hand.gif */
extern const unsigned char icon_Hand[4909];

/* created by reswrap from file images/icon_Pointer.gif */
extern const unsigned char icon_Pointer[4735];

}
