// Automatically generated by build.bat 
// vim: shiftwidth=4 
// vim: ts=4 

package com.errapartengineering.DigNet; 
import java.util.Date;

// Build info. 
public final class BuildInfo { 
	// Build date: Sun Sep 02 05:06:49 EEST 2007
	public final static String buildDate = "2007-09-02 05:06:49";
	// Output log to the serial port 3? Default is false.
	public final static boolean	logToSerial = false;
	// Output log to the server connection? Default is true.
	public final static boolean	logToServer = true;
	// Application, one of "GpsBase", "ModemBox". Default is "GpsBase"
	public final static String application = "GpsBase";
	public final static String compilationArguments = "-logToSerial,+logToServer,application=GpsBase";
} // class Build 
